Updating task execution id next val to use sequence for sqlserver
spring-cloud/spring-cloud-task pull request #783
Opened 2021-05-07 22:41 UTC by cppwfs

resolves TASK-782

2021-05-10 19:22 UTC, mminella requested changes

2021-05-10 19:22 UTC, mminella commented on spring-cloud-task-core/src/main/java/org/springframework/cloud/task/repository/support/TaskSqlServerSequenceMaxValueIncrementer.java
> +public class TaskSqlServerSequenceMaxValueIncrementer extends AbstractSequenceMaxValueIncrementer {
See previous note about removing the `Task` prefix from the name of this class. Also...unit test for this class?

2021-05-28 17:52 UTC, mminella commented on docs/src/main/asciidoc/appendix-task-repository-schema.adoc
> +The resolution is to drop the `TASK_EXECUTION_SEQ` table and create a sequence using the same name.   For example:
Do we want to call out that existing users should set the start with value to be one more than the current value in the sequence table?

2021-05-28 22:23 UTC, cppwfs commented
Rebased, Squashed and Merged with permission of @mminella

2021-05-28 22:23 UTC, closed without merging