Updated readmes to improve copy pastability
spring-cloud/spring-cloud-task pull request #867
Opened 2022-10-05 21:32 UTC by cppwfs

Also added instructions for native compilation for those apps that it is useful

Added documentation for native compilation when using Single Step Batch Processing

Updated documentaiton for native compilation for single app processing

2022-10-06 14:03 UTC, Buzzardo requested changes

2022-10-06 14:03 UTC, Buzzardo commented on docs/src/main/asciidoc/features.adoc
> +To do so, add the process-aot execution and set the spring.cloud.task.single-step-instance-enabled=true as a JVM argument, as follows:
Change to:

To do so, add the `process-aot` execution and set `spring.cloud.task.single-step-instance-enabled=true` as a JVM argument, as follows:

2022-10-06 14:03 UTC, Buzzardo commented on spring-cloud-task-samples/batch-events/README.adoc
> +For example, you can listen for specific job execution events on a specified channel with a Spring Cloud Stream Sink
Hyphenate "job-execution"

2022-10-07 20:53 UTC, cppwfs commented
Fixes applied, Squashed Merged .    Thanks for the review!!!!

2022-10-07 20:53 UTC, closed without merging